sudo: required
dist: trusty
services:
  - docker
  - neo4j

## Cache composer and vendor libraries
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
    fast_finish: true
    include:
        #
        # Define versions of MySQL and MariaDB to test against.
        # mysql 5.6
        - php: 7.2
          env: DB=mysql:5.6
        #
        # Define versions of MySQL and MariaDB to test against.
        # mysql 5.6
        - php: 7.2
          env: DB=mysql:5.7
        #
        # Define versions of MySQL and MariaDB to test against.
        # mysql 5.6
        - php: nightly
          env: DB=mysql:8.0
        # ...
        # mariadb 10.3
        - php: nightly
          env: DB=mariadb:10.3


before_script:
  - chmod +x .travis/install-and-init-db.sh && .travis/install-and-init-db.sh
  - cp .env.travis .env
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate
  - php artisan migrate
  - composer update --prefer-dist
  - npm install
  - npm run dev

script:
  #- phpunit --coverage-clover coverage.xml
  - phpunit

after_script:
  # upload coverage.xml file to Coveralls to analyze it
  # minimal required coverage is set to 80+ %
  # - wget https://github.com/satooshi/php-coveralls/releases/download/v2.1.0/coveralls.phar
  # - php coveralls.phar --verbose


notifications:
email: false
